created accounts app and updated settings
BuildForSDGCohort2/team-078-backend-openmarket-seller pull request #33
Opened 2020-09-20 21:06 UTC by eneotujoe

# Description
The user account app contains the Django custom user model. With this, it is easier to customize the user signup details. Django strongly recommends a custom user model as it is tedious to migrate or customize the default Django User model in production. For e-commerce, email address is used as an identifier, therefore, this account app uses email as a primary means of authentication.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B
# Provide screen shoot to prove the test

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-09-22 13:48 UTC, AjibsBaba requested changes
I thought the model profile is already handling accounts so I don't think an accounts app is needed

2020-09-26 17:16 UTC, donprecious approved these changes

2020-09-29 20:17 UTC, donprecious approved these changes

2020-09-29 20:24 UTC, donprecious approved these changes

2020-09-29 20:24 UTC, merged